name: NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build
        git config user.name mcp-bot
        git config user.email mcp-bot@maritimeconnectivity.net
        git fetch
        git checkout gh-pages
        mv dist/* .
        rm -rf dist/
        git add .
        git commit -m "New application build"
        git push
