name: NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Git Push
      if: ${{ github.event_name == 'push' }}
      run: |
        git config user.name mcp-bot
        git config user.email mcp-bot@maritimeconnectivity.net
        git fetch
        git checkout gh-pages
        mv dist/* .
        rm -rf dist/
        git add index.html main.js*
        if [[ -z $(git --no-pager diff HEAD) ]]; then exit 0; fi 
        git commit -m "New application build"
        git push
      shell: bash
