name: NodeJS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache-dependency-path: ./src/go/go.sum

    - name: Build
      run: |
        npm install
        npm run build:go
        npm run build

    - name: Git Push
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config user.name mcp-bot
        git config user.email mcp-bot@maritimeconnectivity.net
        git fetch
        git checkout gh-pages
        mv dist/* .
        rm -rf dist/
        git add index.html main.js* main.js.LICENSE.txt wasm_exec.js main.wasm
        if [[ -z $(git --no-pager diff HEAD) ]]; then exit 0; fi 
        git commit -m "New application build"
        git push
      shell: bash
